services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password
      MYSQL_DATABASE: userschema        # Database to create (optional)
    ports:
      - "3308:3306"  # Exposes MySQL on port 3308 of the host
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  # Spring Cloud Config Server service
  config-server:
    image: config-server:latest
    container_name: config-server
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/mathanparamasivan/central-config-repo # Replace with actual Git repo URL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/userschema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_SERVER_PORT: 8888
      LATEST_PROP: latest
    ports:
      - "8888:8888"
    depends_on:
      - mysql
    restart: always
    networks:
      - default

  # Application container
  patient-service:
    build:
      context: .
      dockerfile: dockerfile  # Specify the path to your Dockerfile if needed
    container_name: patient-service
    environment:
      SPRING_PROFILES_ACTIVE: test  # Set the active Spring profile to 'docker'
      SPRING_CLOUD_CONFIG_URI: http://172.26.192.1:8888  # Set the URI for the Spring Cloud Config Server
    ports:
      - "8081:8081"  # Exposes app on port 8081 of the host
    depends_on:
      - config-server
    restart: on-failure:3
    networks:
      - default

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
