name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - master   # or any branch you want to trigger on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1   # your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t patient.service:latest .

      - name: Tag Docker Image
        run: |
          docker tag patient.service:latest 123456789012.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 123456789012.dkr.ecr.ap-south-1.amazonaws.com/patient.service:latest
